version: '3.1'
services:
  stats-server:
    build: ./stats-service/stats-server
    image: stats-server-image
    container_name: stats-server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats_db

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats_db
      - POSTGRES_USER=ivan
      - POSTGRES_PASSWORD=12345

  ewm-service:
    build: ./ewm-service
    image: ewm-service-image
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - stats-server.url=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm_db

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=ewm_db
      - POSTGRES_USER=ivan
      - POSTGRES_PASSWORD=12345